dist: xenial

language: python

python:
  - "3.6"
  - "3.7"

install:
  - "pip install pytest flake8 coverage pytest-cov python-coveralls"
  - "pip install -r requirements.txt"

script:
  - "python setup.py install"
  - "py.test tests/tests.py ate --cov ate --cov-report term-missing"
  - "flake8 ate"

after_success:
  - "coveralls"
